// Define the type for a single stock item
export interface Stock {
  id: number;
  symbol: string;
  name: string;
  marketCap: string;
  sector: string;
  industry: string;
  // Add other properties if your stock objects have them
}
export const stocks: Stock[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    marketCap: "3.2T",
    sector: "Technology",
    industry: "Consumer Electronics",
    id: 1,
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corp.",
    marketCap: "3.4T",
    sector: "Technology",
    industry: "Software—Infrastructure",
    id: 2,
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc. (Class A)",
    marketCap: "2.2T",
    sector: "Communication Services",
    industry: "Internet Content & Information",
    id: 3,
  },
  {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    marketCap: "2.0T",
    sector: "Consumer Discretionary",
    industry: "Internet Retail",
    id: 4,
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corp.",
    marketCap: "3.1T",
    sector: "Technology",
    industry: "Semiconductors",
    id: 5,
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    marketCap: "580B",
    sector: "Consumer Discretionary",
    industry: "Auto Manufacturers",
    id: 6,
  },
  {
    symbol: "META",
    name: "Meta Platforms Inc. (Class A)",
    marketCap: "1.3T",
    sector: "Communication Services",
    industry: "Social Media",
    id: 7,
  },
  {
    symbol: "BRK.B",
    name: "Berkshire Hathaway Inc. (Class B)",
    marketCap: "900B",
    sector: "Financials",
    industry: "Insurance—Diversified",
    id: 8,
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    marketCap: "550B",
    sector: "Financials",
    industry: "Banks—Diversified",
    id: 9,
  },
  {
    symbol: "V",
    name: "Visa Inc. (Class A)",
    marketCap: "570B",
    sector: "Financials",
    industry: "Credit Services",
    id: 10,
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Inc.",
    marketCap: "480B",
    sector: "Healthcare",
    industry: "Healthcare Plans",
    id: 11,
  },
  {
    symbol: "JNJ",
    name: "Johnson & Johnson",
    marketCap: "400B",
    sector: "Healthcare",
    industry: "Drug Manufacturers—General",
    id: 12,
  },
  {
    symbol: "WMT",
    name: "Walmart Inc.",
    marketCap: "500B",
    sector: "Consumer Defensive",
    industry: "Discount Stores",
    id: 13,
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corp.",
    marketCap: "450B",
    sector: "Energy",
    industry: "Oil & Gas Integrated",
    id: 14,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 15,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 16,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 17,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 18,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 19,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 20,
  },

  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 21,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 22,
  },

  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 23,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 24,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 25,
  },
  {
    symbol: "PG",
    name: "Procter & Gamble Co.",
    marketCap: "380B",
    sector: "Consumer Defensive",
    industry: "Household & Personal Products",
    id: 26,
  },
];
