ALTER TABLE workspaces ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE workspaces ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE workspaces ALTER COLUMN deleted_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE forms ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE forms ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE forms ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE forms ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE form_elements ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE form_elements ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;
